# Generated by Django 5.1.3 on 2024-11-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowedBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentLRN', models.IntegerField()),
                ('studentGLevel', models.CharField(max_length=50)),
                ('studentSection', models.CharField(max_length=50)),
                ('dateBorrowed', models.DateField()),
                ('dateReturned', models.DateField()),
                ('bookNumber', models.IntegerField()),
            ],
        ),
    ]
