# Generated by Django 5.1.3 on 2024-11-21 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BorrowedBooks', '0003_borrowedbooks_booknumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowedbooks',
            name='book',
        ),
    ]
