# Generated by Django 5.1.3 on 2024-11-25 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BorrowedBooks', '0004_remove_borrowedbooks_book'),
        ('bookinfos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowedbooks',
            name='bookNumber',
        ),
        migrations.AddField(
            model_name='borrowedbooks',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookinfos.bookinfo'),
            preserve_default=False,
        ),
    ]
