# Generated by Django 5.1.3 on 2024-11-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newSection', models.CharField(blank=True, default='Others', max_length=20)),
            ],
        ),
    ]
